/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch Clinical Precision System Color Palette
        'inverse-primary': '#80d5cb',
        'inverse-on-surface': '#eef1f0',
        'surface-container-low': '#f1f4f3',
        'error': '#ba1a1a',
        'secondary-fixed': '#d5e3fc',
        'error-container': '#ffdad6',
        'outline-variant': '#bdc9c6',
        'on-tertiary-fixed-variant': '#72361b',
        'outline': '#6e7977',
        'on-surface-variant': '#3e4947',
        'on-tertiary': '#ffffff',
        'surface-bright': '#f7faf8',
        'secondary': '#515f74',
        'surface': '#f7faf8',
        'on-surface': '#181c1c',
        'tertiary-fixed-dim': '#ffb598',
        'on-error-container': '#93000a',
        'surface-container-high': '#e5e9e7',
        'on-primary-fixed': '#00201d',
        'secondary-container': '#d5e3fc',
        'on-primary-container': '#a3faef',
        'on-primary-fixed-variant': '#00504a',
        'primary-fixed': '#9cf2e8',
        'background': '#f7faf8',
        'primary-container': '#0f766e',
        'on-tertiary-fixed': '#370e00',
        'surface-variant': '#e0e3e1',
        'on-secondary-fixed-variant': '#3a485b',
        'on-background': '#181c1c',
        'tertiary': '#7f4025',
        'on-secondary-fixed': '#0d1c2e',
        'on-tertiary-container': '#ffe5db',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#80d5cb',
        'surface-container-highest': '#e0e3e1',
        'surface-container': '#ebefed',
        'tertiary-fixed': '#ffdbce',
        'surface-tint': '#006a63',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#9c573a',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#b9c7df',
        'surface-dim': '#d7dbd9',
        'on-secondary-container': '#57657a',
        'inverse-surface': '#2d3130',
        'primary': '#005c55',
      },
      borderRadius: {
        'DEFAULT': '0.375rem',  // 6px - slightly more modern
        'lg': '0.5rem',         // 8px
        'xl': '0.75rem',        // 12px
        'full': '9999px',
      },
      spacing: {
        'xs': '6px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'base': '8px',
        'touch-target-min': '44px',
      },
      maxWidth: {
        'container': '640px',
      },
      fontFamily: {
        'sans': ['-apple-system', 'BlinkMacSystemFont', 'Inter', 'SF Pro Text', 'Segoe UI', 'Roboto', 'system-ui', 'sans-serif'],
        'headline': ['-apple-system', 'BlinkMacSystemFont', 'Inter', 'SF Pro Display', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        // Headlines - more minimal
        'headline-xl': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-xl-mobile': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['17px', { lineHeight: '24px', fontWeight: '600' }],
        // Body - smaller, tighter
        'body-lg': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-xs': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        // Labels - minimal
        'label-lg': ['15px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['13px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        'header': '0 1px 8px rgba(0, 0, 0, 0.04)',
        'bottom-nav': '0 -1px 8px rgba(0, 0, 0, 0.04)',
      },
      backdropBlur: {
        'xl': '20px',
      },
    },
  },
  plugins: [],
}
